<?xml version="1.0"?>
<package format="3">
  <name>fss_sensing</name>
  <version>0.1.1</version>
  <description>ROS 2 sensing wrappers for FastSwarmSim.</description>
  <maintainer email="shupeixuan@qq.com">Peixuan Shu</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>ament_index_cpp</depend>
  <depend>fss_time</depend>
  <depend>geometry_msgs</depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <depend>libopencv-dev</depend>
  <depend>libglew-dev</depend>
  <depend>libglfw3-dev</depend>
  <depend>yaml-cpp</depend>
  <depend>nav_msgs</depend>
  <depend>libpcl-all-dev</depend>
  <depend>pcl_conversions</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
