<?xml version="1.0"?>
<package format="3">
  <name>fss_time</name>
  <version>0.1.1</version>
  <description>ZeroMQ based conservative lock-step simulation time for FastSwarmSim.</description>
  <maintainer email="shupeixuan@qq.com">Peixuan Shu</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>builtin_interfaces</depend>
  <depend>fss_time_interfaces</depend>
  <depend>libzmq3-dev</depend>
  <depend>rclcpp</depend>
  <depend>rosgraph_msgs</depend>
  <depend>std_srvs</depend>
  <depend>std_msgs</depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>python3-pyqt5</exec_depend>
  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
